/**
 * Config YAML generator for SigCLI.
 * Uses template literals (NOT YAML.stringify) to preserve comments.
 */

export interface InitOptions {
    mode: 'browser' | 'browserless';
    channel: string;
    execPath?: string;
    browserDataDir: string;
    credentialsDir: string;
    headlessTimeout: number;
    visibleTimeout: number;
    waitUntil: string;
}

/**
 * Generate a commented YAML config string from the given options.
 */
export function generateConfigYaml(options: InitOptions): string {
    const modeLine =
        options.mode === 'browserless'
            ? 'mode: browserless                          # No browser on this machine — use sig sync pull'
            : 'mode: browser                              # Use "browserless" on remote/headless machines';

    const execPathLine = options.execPath
        ? `\n  execPath: '${options.execPath}'              # Detected browser binary`
        : '';

    return `# SigCLI configuration
# Generated by "sig init". Providers are added via "sig login <url>".

version: 2

${modeLine}

browser:
  browserDataDir: ${options.browserDataDir}
  channel: ${options.channel}${execPathLine}
  headlessTimeout: ${options.headlessTimeout}
  visibleTimeout: ${options.visibleTimeout}
  waitUntil: ${options.waitUntil}

storage:
  credentialsDir: ${options.credentialsDir}

# Providers are auto-provisioned by "sig login <url>".
# Add entries here for custom extract/apply rules or fine-tuning.
#
# Example:
#   my-service:
#     domains:
#       - service.example.com
#     entryUrl: https://service.example.com/
#     strategy: browser
#     extract:
#       - from: cookies
#         name: session
#         key: "*"
#     apply:
#       - in: header
#         name: Cookie
#         value: "\${session}"
#     # ttl: 12h                         # Optional: credential lifetime
#     # loginMode: cdp                   # Optional: auto|cdp|headless|visible
#     # required:                        # Optional: wait for specific cookies
#     #   - session.my_cookie
providers: {}
`;
}
